spring.application.name=demo
server.port=8080

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/stevanProjects
spring.datasource.username=stevanProjects
spring.datasource.password=testing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect